jahiacom_component=jahiacom - Components

jahiacom_helloWorld=Hello World
jahiacom_helloWorld.name=Name

jahiacom_helloCard=Hello Card
jahiacom_helloCard.title=Title
jahiacom_helloCard.illustration=Illustration
jahiacom_helloCard.illustration.code=A developer coding
jahiacom_helloCard.illustration.coffee=Buying coffee
jahiacom_helloCard.illustration.interface=Consulting an interface
jahiacom_helloCard.illustration.read=Looking at a bookshelf
jahiacom_helloCard.illustration.write=Writing with a typewriter

jahiacom_languageSwitcher=Language Switcher

jahiacom_hero=Hero
jahiacom_hero.subtitle=Subtitle
jahiacom_hero.image=Image
jahiacom_hero.image.ui.tooltip=If "Call to Action" is set, the image will be next to the text column. Otherwise, the image will be used in full width.
jahiacom_hero.j_linkType=Call to Action
jahiacom_hero.ctaLabel=Call to Action Label
jahiacom_hero.ctaLabel.ui.tooltip=Leave blank to use the page title when "Call to Action" is set to "internal". Ignored when set to "none".
jahiacom_hero.background=Background variation
jahiacom_hero.background.ui.tooltip=Clear for plain color, set a value for a variation.
