jahiacommix_container=Container Theme
jahiacommix_container.subtitle=Subtitle
jahiacommix_container.theme=Color theme
jahiacommix_container.theme.day=Day (white)
jahiacommix_container.theme.cloudy=Cloudy (light gray)
jahiacommix_container.theme.night=Night (dark blue)
jahiacommix_container.background=Background variation
jahiacommix_container.background.ui.tooltip=Useful to break the visual monotony. Clear the field for plain color.
jahiacommix_container.background.plusses=Plusses (Night)
jahiacommix_container.background.stripes=Stripes (Night)
jahiacommix_container.background.matrix=Matrix (Night)
jahiacommix_container.background.bottom-grid=Bottom Grid (Day and Cloudy)

jahiacommix_component=Jahia.com Component

jahiacommix_content=Jahia.com Content

jahiacommix_menuCTAs=Configure menu CTAs
jahiacommix_menuCTAs.primaryCTALink=Primary CTA link target
jahiacommix_menuCTAs.primaryCTALink.ui.tooltip=The primary CTA is the one in blue, leave empty to hide.
jahiacommix_menuCTAs.primaryCTALabel=Primary CTA label
jahiacommix_menuCTAs.primaryCTALabel.ui.tooltip=The page title is used if left empty.
jahiacommix_menuCTAs.secondaryCTALink=Secondary CTA link target
jahiacommix_menuCTAs.secondaryCTALink.ui.tooltip=The secondary CTA is the one in outline, leave empty to hide.
jahiacommix_menuCTAs.secondaryCTALabel=Secondary CTA label
jahiacommix_menuCTAs.secondaryCTALabel.ui.tooltip=The page title is used if left empty.

jahiacommix_seoOptions=Additional SEO options
jahiacommix_seoOptions.htmlTitle=HTML title
jahiacommix_seoOptions.htmlTitle.ui.tooltip=Used in the &lt;title&gt; tag and as OpenGraph title. The page title is used if left empty.
jahiacommix_seoOptions.jsonLd=JSON for Linking Data (JSON-LD)
jahiacommix_seoOptions.jsonLd.ui.tooltip=Page-level JSON-LD data. See json-ld.org for more information. Do NOT include the &lt;script&gt; tag.
jahiacommix_seoOptions.noindex=Disable search-engine indexing (noindex)
jahiacommix_seoOptions.nofollow=Disable search-engine subsequent crawling (nofollow)

jahiacommix_cta=Call to Action
jahiacommix_cta.ctaType=Type
jahiacommix_cta.ctaLabel=Label
jahiacommix_cta.ctaLabel.ui.tooltip=Leave blank to use the page title when "Call to Action" is set to "internal". Ignored when set to "none".
jahiacommix_cta.ctaVariant=Variant
jahiacommix_cta.ctaVariant.primary=Primary (blue)
jahiacommix_cta.ctaVariant.secondary=Secondary (outline)

jahiacom_partner=Partner
jahiacom_partner.certification=Certification
jahiacom_partner.certification.silver=Silver Partner
jahiacom_partner.certification.gold=Gold Partner
jahiacom_partner.certification.diamond=Diamond Partner
jahiacom_partner.countries=Countries
jahiacom_partner.description=Description
jahiacom_partner.logo=Logo
jahiacom_partner.website=Website

jahiacom_partnerCategory=Partner Category

jahiacom_resource=Resource (download form)
jahiacom_resource.description=Description
jahiacom_resource.description.ui.tooltip=Description of the resource, shown on the left-hand side of the download form.
jahiacom_resource.form=Form
jahiacom_resource.form.ui.tooltip=Form to fill in to download the resource.

jahiacom_resourceCategory=Resource Category
jahiacom_resourceCategory.icon=Icon
jahiacom_resourceCategory.icon.ui.tooltip=Icon to display in the resource category badge. Use a SVG file for best results.
jahiacom_resourceCategory.subtitle=Subtitle
jahiacom_resourceCategory.subtitle.ui.tooltip=Subtitle displayed in full-page view of the category.

jahiacom_accordion=Accordion (e.g. FAQ)

jahiacom_card=Card
jahiacom_card.body=Body
jahiacom_card.icon=Icon
jahiacom_card.icon.ui.tooltip=Small optional icon displayed before the title.

jahiacom_containerReference=Container Reference
jahiacom_containerReference.container=Reference

jahiacom_contentStack=Content Stack

jahiacom_heroWithImage=Hero With Image
jahiacom_heroWithImage.subtitle=Subtitle
jahiacom_heroWithImage.image=Image

jahiacom_heroWithoutImage=Hero Without Image
jahiacom_heroWithoutImage.subtitle=Subtitle

jahiacom_languageSwitcher=Language Switcher

jahiacom_logoCarousel=Logo Carousel
jahiacom_logoCarousel.mode=Color mode
jahiacom_logoCarousel.mode.ui.tooltip=Apply a color filter to the logos.
jahiacom_logoCarousel.mode.color=Color (logos are kept as is)
jahiacom_logoCarousel.mode.mono=Monochrome (logos are masked with a dark color)
jahiacom_logoCarousel.logos=Logos
jahiacom_logoCarousel.logos.ui.tooltip=Make sure that all logos have an alt text.

jahiacom_panel=Panel
jahiacom_panel.body=Body
jahiacom_panel.image=Image
jahiacom_panel.swap=Swap the image and the body on desktop
jahiacom_panel.swap.ui.tooltip=Swap even-numbered panels for a good effect.

jahiacom_section=Section
jahiacom_section.subtitle=Subtitle
jahiacom_section.columns=Number of columns
jahiacom_section.columns.ui.tooltip=Number and size of columns. Use "Jahia - Lists > List of content items" to group items in the same column.
jahiacom_section.columns.100=1
jahiacom_section.columns.50-50=2 (50% / 50%)
jahiacom_section.columns.67-33=2 (67% / 33%)
jahiacom_section.columns.33-67=2 (33% / 67%)
jahiacom_section.columns.irregular-67-33=2 (Alternating 67% / 33%)
jahiacom_section.columns.33-33-33=3 (33% / 33% / 33%)
jahiacom_section.columns.25-25-25-25=4 (25% / 25% / 25% / 25%)
jahiacom_section.columns.irregular-1-2=1 - 2 - 1 - ... (Irregular grid)
jahiacom_section.columns.irregular-3-2=2 - 3 - 2 - ... (Irregular grid)
jahiacom_section.width=Width
jahiacom_section.width.ui.tooltip=Width of the container when on desktop. Ignored on mobile.
jahiacom_section.width.100=Full
jahiacom_section.width.75=3/4
jahiacom_section.width.50=Half
jahiacom_section.gap=Gap
jahiacom_section.gap.ui.tooltip=Gap between items.
jahiacom_section.gap.0=None (Use the "borderless" view on children!)
jahiacom_section.gap.1=Regular
jahiacom_section.gap.2=Double (Best for Panels)

jahiacom_testimony=Testimony
jahiacom_testimony.author=Author
jahiacom_testimony.quote=Quote
jahiacom_testimony.image=Image
jahiacom_testimony.image.ui.tooltip=For best results, use the default view if the image is a portrait, and the cover view if the image is a landscape.

jahiacom_pageArea=Page Area

jahiacom_pageFooter=Page Footer
jahiacom_pageFooter.bottomLinks=Links at the very end of the footer (usually legal links)

jahiacom_footerColumns=Footer Columns

jahiacom_footerColumn=Footer Column
jahiacom_footerColumn.links=Links

jahiacom_footerIcons=Footer Icons

jahiacom_footerIcon=Footer Icon
jahiacom_footerIcon.icon=Icon
jahiacom_footerIcon.icon.ui.tooltip=Icon to display in the footer. Use a SVG file for best results.
jahiacom_footerIcon.href=External link target
jahiacom_footerIcon.href.ui.tooltip=Leave empty to display the icon without a link.

jahiacommix_gadget=Jahia.com Gadgets (use with caution!)

jahiacom_stylesheet=Stylesheet
jahiacom_stylesheet.css=CSS code
jahiacom_stylesheet.css.ui.tooltip=USE CAUTIOUSLY! This CSS code will be added to a <code>&lt;style&gt;</code> tag directly in the HTML page. Please make sure it is valid and minified.

jahiacommix_customCss=Custom CSS
jahiacommix_customCss.stylesheets=Stylesheets to apply
