jahiacommix_component=Components (add in containners)

jahiacommix_container=Containers (add on the page)
jahiacommix_container.subtitle=Subtitle
jahiacommix_container.theme=Color theme
jahiacommix_container.theme.day=Day (white)
jahiacommix_container.theme.cloudy=Cloudy (light gray)
jahiacommix_container.theme.night=Night (dark blue)
jahiacommix_container.background=Background variation
jahiacommix_container.background.ui.tooltip=Clear for plain color, set a value for a variation.
jahiacommix_container.background.plusses=Plusses (Night)
jahiacommix_container.background.stripes=Stripes (Night)

jahiacommix_menuCTAs=Configure menu CTAs
jahiacommix_menuCTAs.primaryCTALink=Primary CTA link target
jahiacommix_menuCTAs.primaryCTALink.ui.tooltip=The primary CTA is the one in blue, leave empty to hide.
jahiacommix_menuCTAs.primaryCTALabel=Primary CTA label
jahiacommix_menuCTAs.primaryCTALabel.ui.tooltip=The page title is used if left empty.
jahiacommix_menuCTAs.secondaryCTALink=Secondary CTA link target
jahiacommix_menuCTAs.secondaryCTALink.ui.tooltip=The secondary CTA is the one in outline, leave empty to hide.
jahiacommix_menuCTAs.secondaryCTALabel=Secondary CTA label
jahiacommix_menuCTAs.secondaryCTALabel.ui.tooltip=The page title is used if left empty.

jahiacommix_seoOptions=Additional SEO options
jahiacommix_seoOptions.jsonLd=JSON for Linking Data (JSON-LD)
jahiacommix_seoOptions.jsonLd.ui.tooltip=Page-level JSON-LD data. See json-ld.org for more information. Do NOT include the &lt;script&gt; tag.
jahiacommix_seoOptions.noindex=Disable search-engine indexing (noindex)
jahiacommix_seoOptions.nofollow=Disable search-engine subsequent crawling (nofollow)

jahiacommix_cta=Call to Action
jahiacommix_cta.ctaType=Type
jahiacommix_cta.ctaLabel=Label
jahiacommix_cta.ctaLabel.ui.tooltip=Leave blank to use the page title when "Call to Action" is set to "internal". Ignored when set to "none".
jahiacommix_cta.ctaVariant=Variant
jahiacommix_cta.ctaVariant.primary=Primary (blue)
jahiacommix_cta.ctaVariant.secondary=Secondary (outline)

jahiacom_accordion=Accordion (e.g. FAQ)

jahiacom_card=Card
jahiacom_card.body=Body

jahiacom_hero=Hero
jahiacom_hero.image=Image

jahiacom_heroWithoutImage=Hero Without Image

jahiacom_languageSwitcher=Language Switcher

jahiacom_logoCarousel=Logo Carousel
jahiacom_logoCarousel.mode=Color mode
jahiacom_logoCarousel.mode.ui.tooltip=Apply a color filter to the logos.
jahiacom_logoCarousel.mode.color=Color (logos are kept as is)
jahiacom_logoCarousel.mode.mono=Monochrome (logos are masked with a dark color)
jahiacom_logoCarousel.logos=Logos
jahiacom_logoCarousel.logos.ui.tooltip=The value in parentheses is the alt text for the image. Make sure that all logos have an alt text. You can upload new logos in Media > /files/logos/.

jahiacom_panel=Panel
jahiacom_panel.image=Image
jahiacom_panel.swap=Swap the image and the body on desktop
jahiacom_panel.swap.ui.tooltip=Swap even-numbered panels for a good effect.

jahiacom_section=Section
jahiacom_section.columns=Number of columns
jahiacom_section.columns.ui.tooltip=Number and size of columns. Use "Jahia - Lists > List of content items" to group items in the same column.
jahiacom_section.columns.100=1
jahiacom_section.columns.50-50=2 (50% / 50%)
jahiacom_section.columns.67-33=2 (67% / 33%)
jahiacom_section.columns.33-67=2 (33% / 67%)
jahiacom_section.columns.33-33-33=3 (33% / 33% / 33%)
jahiacom_section.columns.25-25-25-25=4 (25% / 25% / 25% / 25%)
jahiacom_section.columns.irregular-3-2=3 - 2 - 3 - ... (Irregular grid)
jahiacom_section.width=Width
jahiacom_section.width.ui.tooltip=Width of the container when on desktop. Ignored on mobile.
jahiacom_section.width.100=Full
jahiacom_section.width.75=3/4
jahiacom_section.width.50=Half
jahiacom_section.gap=Gap
jahiacom_section.gap.ui.tooltip=Gap between items.
jahiacom_section.gap.1=Regular
jahiacom_section.gap.2=Double (Best for Panels)
