name: Build and Push

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: corepack enable
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          name: package.tgz
          path: dist/package.tgz

      # If the build is successful and the branch is main, push the module to Jahia
      - if: github.ref == 'refs/heads/main'
        run: yarn jahia-deploy
        env:
          JAHIA_USER: ${{ secrets.JAHIA_USER }}
          JAHIA_HOST: ${{ secrets.JAHIA_HOST }}
          JAHIA_IGNORE_CHECKS: "false"

  lighthouse:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: browser-actions/setup-chrome@v1
      - run: npx lighthouse@12 '${{ secrets.JAHIA_HOST }}/sites/jahiacom/home.html' --quiet --chrome-flags='--headless' --output=json | jq '.categories | map_values(.score)'
