name: Build and Push

on: push

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v4
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - uses: actions/upload-artifact@v7
        with:
          path: dist/package.tgz
          archive: false
