name: Comment PR
on:
  pull_request_target:
    branches:
      - main
jobs:
  comment-pr:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
      - run: npx chachalog@^0.5.0 comment-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
